/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.component;

import javax.swing.JOptionPane;
import utils.SendMail;
import javax.swing.Timer;

/**
 *
 * @author ADMIN
 */
public class OTP extends javax.swing.JFrame {
     private String email;
    private String otpCode;
    private long otpCreatedTime;
    private Timer timer; // THÊM biến này
    private Timer resendTimer;
    private int countDownSeconds = 5 * 60;
    private boolean canResendOtp = true;
    private int resendCountdown = 0;


    /**
     * Creates new form OTP
     */
     public OTP(String email, String otpCode) {
        this.email = email;
        this.otpCode = otpCode;
        this.otpCreatedTime = System.currentTimeMillis();
        initComponents();
        setLocationRelativeTo(null);
        startCountdown();
        enableResendOtp();
    }
     
     private void startCountdown() {
        if (timer != null && timer.isRunning()) {
            timer.stop();
        }
        countDownSeconds = 5 * 60; // reset về 5 phút
        updateTimeLabel();

        timer = new Timer(1000, e -> {
            countDownSeconds--;
            updateTimeLabel();
            if (countDownSeconds <= 0) {
                timer.stop();
                lblTime.setText("00:00");
                JOptionPane.showMessageDialog(this, "Mã OTP đã hết hạn! Vui lòng bấm gửi lại mã.");
            }
        });
        timer.start();
    }

    private void updateTimeLabel() {
        int minutes = countDownSeconds / 60;
        int seconds = countDownSeconds % 60;
        lblTime.setText(String.format("%02d:%02d", minutes, seconds));
    }
    
    private void disableResendOtp() {
        canResendOtp = false;
        resendCountdown = 60;
        lblGuiLaiOTP.setEnabled(false);
        lblGuiLaiOTP.setText("Gửi lại mã (" + resendCountdown + "s)");
        // Dừng timer cũ nếu có
        if (resendTimer != null && resendTimer.isRunning()) {
            resendTimer.stop();
        }
        resendTimer = new Timer(1000, e -> {
            resendCountdown--;
            lblGuiLaiOTP.setText("Gửi lại mã (" + resendCountdown + "s)");
            if (resendCountdown <= 0) {
                resendTimer.stop();
                enableResendOtp();
            }
        });
        resendTimer.start();
    }

    // Gọi hàm này khi cho phép gửi lại OTP
    private void enableResendOtp() {
        canResendOtp = true;
        lblGuiLaiOTP.setEnabled(true);
        lblGuiLaiOTP.setText("Chưa nhận được mã OTP?");
        if (resendTimer != null && resendTimer.isRunning()) {
            resendTimer.stop();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtOTP = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblGuiLaiOTP = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setText("Quay Lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnContinue.setText("Tiếp tục");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        jLabel2.setText("Nhập OTP");

        lblGuiLaiOTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sync.png"))); // NOI18N
        lblGuiLaiOTP.setText("chưa nhận được mã otp ?");
        lblGuiLaiOTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGuiLaiOTPMouseClicked(evt);
            }
        });

        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 0, 0));
        lblTime.setText("00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnContinue))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGuiLaiOTP)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(101, 101, 101)
                                    .addComponent(lblTime))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGuiLaiOTP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnContinue)))
        );

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("OTP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        String inputOtp = txtOTP.getText().trim();
        if (inputOtp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã xác thực!");
            txtOTP.requestFocus();
            return;
        }
        // Kiểm tra hết hạn
        long now = System.currentTimeMillis();
        if (now - otpCreatedTime > 5 * 60 * 1000) { // lớn hơn 5 phút
            JOptionPane.showMessageDialog(this, "Mã OTP đã hết hạn! Vui lòng bấm gửi lại mã.");
            return;
        }
        if (!inputOtp.equals(otpCode)) {
            JOptionPane.showMessageDialog(this, "Mã xác thực không đúng!");
            txtOTP.requestFocus();
            return;
        }
        // Nếu đúng, mở form đổi mật khẩu, truyền email sang
        JOptionPane.showMessageDialog(this, "Xác thực thành công! Bạn có thể đặt lại mật khẩu.");
        passnew changePassForm = new passnew(email); // Đảm bảo đã có constructor passnew(String email)
        changePassForm.setLocationRelativeTo(null);
        changePassForm.setVisible(true);
        this.dispose(); // đóng form OTP
    }//GEN-LAST:event_btnContinueActionPerformed

    private void lblGuiLaiOTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuiLaiOTPMouseClicked
        if (!canResendOtp) return;
        String newOtp = String.valueOf((int)(Math.random() * 900000) + 100000); // mã 6 số
        String subject = "Mã xác thực lấy lại mật khẩu";
        String body = """
<!DOCTYPE html>
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en">
<head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        * { box-sizing: border-box; }
        body { margin: 0; padding: 0; }
        a[x-apple-data-detectors] { color: inherit !important; text-decoration: inherit !important; }
        #MessageViewBody a { color: inherit; text-decoration: none; }
        p { line-height: inherit }
        .desktop_hide, .desktop_hide table { mso-hide: all; display: none; max-height: 0px; overflow: hidden; }
        .image_block img+div { display: none; }
        sup, sub { font-size: 75%%; line-height: 0; }
        @media (max-width:620px) {
            .desktop_hide table.icons-inner,
            .social_block.desktop_hide .social-table { display: inline-block !important; }
            .icons-inner { text-align: center; }
            .icons-inner td { margin: 0 auto; }
            .mobile_hide { display: none; }
            .row-content { width: 100%% !important; }
            .stack .column { width: 100%%; display: block; }
            .mobile_hide { min-height: 0; max-height: 0; max-width: 0; overflow: hidden; font-size: 0px; }
            .desktop_hide, .desktop_hide table { display: table !important; max-height: none !important; }
        }
    </style>
</head>
<body style="margin:0; background-color:#091548; padding:0; -webkit-text-size-adjust:none; text-size-adjust:none;">
    <table width="100%%" border="0" cellpadding="0" cellspacing="0" style="background-color:#091548;">
        <tbody>
            <tr>
                <td>
                    <table align="center" width="100%%" border="0" cellpadding="0" cellspacing="0" style="background-color:#091548; background-image:url('https://d1oco4z2z1fhwp.cloudfront.net/templates/default/3986/background_2.png'); background-position:center top; background-repeat:repeat;">
                        <tbody>
                            <tr>
                                <td>
                                    <table align="center" border="0" cellpadding="0" cellspacing="0" style="width:600px; margin:0 auto; color:#000000;">
                                        <tbody>
                                            <tr>
                                                <td width="100%%" style="font-weight:400; text-align:left; padding-bottom:15px; padding-left:10px; padding-right:10px; padding-top:5px; vertical-align:top;">
                                                    <div style="height:8px;line-height:8px;font-size:1px;">&#8202;</div>
                                                    <table width="100%%" border="0" cellpadding="0" cellspacing="0">
                                                        <tr>
                                                            <td style="width:100%%;padding-right:0px;padding-left:0px;">
                                                                <div align="center" style="max-width:232px;">
                                                                    <img src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/3986/header3.png" style="display:block; height:auto; border:0; width:100%%;" width="232" alt="Main Image" title="Main Image">
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table width="100%%" border="0" cellpadding="0" cellspacing="0">
                                                        <tr>
                                                            <td style="padding-bottom:15px;padding-top:10px;">
                                                                <div style="color:#ffffff;font-family:'Varela Round', 'Trebuchet MS', Helvetica, sans-serif;font-size:30px;line-height:1.2;text-align:center;">
                                                                    <p style="margin:0;"><span>OTP Verification</span></p>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table width="100%%" border="0" cellpadding="5" cellspacing="0">
                                                        <tr>
                                                            <td>
                                                                <div style="color:#ffffff;font-family:'Varela Round', 'Trebuchet MS', Helvetica, sans-serif;font-size:16px;line-height:1.5;text-align:center;">
                                                                    <p style="margin:0;">Bạn vừa yêu cầu xác thực tài khoản.</p>
                                                                    <p style="margin:0;">Vui lòng sử dụng mã OTP bên dưới để tiếp tục:</p>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <!-- OTP Block -->
                                                    <table width="100%%" border="0" cellpadding="0" cellspacing="0">
                                                        <tr>
                                                            <td align="center" style="padding:20px 0;">
                                                                <span style="display:inline-block;background:#eaf6fb;color:#3498db;font-size:32px;font-weight:bold;padding:14px 42px;border-radius:10px;letter-spacing:12px;border:2px dashed #3498db;">
                                                                    %s
                                                                </span>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <!-- End OTP Block -->
                                                    <table width="100%%" border="0" cellpadding="0" cellspacing="0">
                                                        <tr>
                                                            <td align="center" style="padding-bottom:10px;">
                                                                <div style="color:#7f96ef;font-family:'Varela Round', 'Trebuchet MS', Helvetica, sans-serif;font-size:14px;line-height:1.5;text-align:center;">
                                                                    <p style="margin:0;">Mã OTP có hiệu lực trong vòng <b>5 phút</b>.</p>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table width="100%%" border="0" cellpadding="0" cellspacing="0">
                                                        <tr>
                                                            <td style="padding-bottom:15px;padding-left:10px;padding-right:10px;padding-top:10px;">
                                                                <div align="center">
                                                                    <table border="0" cellpadding="0" cellspacing="0" width="60%%">
                                                                        <tr>
                                                                            <td style="font-size:1px;line-height:1px;border-top:1px solid #5A6BA8;"><span>&#8202;</span></td>
                                                                        </tr>
                                                                    </table>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table width="100%%" border="0" cellpadding="0" cellspacing="0">
                                                        <tr>
                                                            <td style="padding-bottom:10px;padding-left:25px;padding-right:25px;padding-top:10px;">
                                                                <div style="color:#7f96ef;font-family:'Varela Round', 'Trebuchet MS', Helvetica, sans-serif;font-size:14px;line-height:1.5;text-align:center;">
                                                                    <p style="margin:0;"><strong>Nếu bạn không yêu cầu mã OTP?</strong></p>
                                                                    <p style="margin:0;">Bạn có thể bỏ qua email này.</p>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <div style="height:30px;line-height:30px;font-size:1px;">&#8202;</div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <!-- Footer -->
                    <table align="center" width="100%%" border="0" cellpadding="0" cellspacing="0">
                        <tbody>
                            <tr>
                                <td>
                                    <table align="center" border="0" cellpadding="0" cellspacing="0" style="width:600px; margin:0 auto; color:#000000;">
                                        <tbody>
                                            <tr>
                                                <td width="100%%" style="font-weight:400; text-align:left; padding-bottom:15px; padding-left:10px; padding-right:10px; padding-top:15px; vertical-align:top;">
                                                    <table width="100%%" border="0" cellpadding="5" cellspacing="0">
                                                        <tr>
                                                            <td>
                                                                <div align="center" style="max-width:145px;">
                                                                    <img src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/3986/logo.png" style="display:block; height:auto; border:0; width:100%%;" width="145" alt="Your Logo" title="Tshat">
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table width="100%%" border="0" cellpadding="0" cellspacing="0">
                                                        <tr>
                                                            <td style="padding-bottom:15px;padding-left:10px;padding-right:10px;padding-top:15px;">
                                                                <div align="center">
                                                                    <table border="0" cellpadding="0" cellspacing="0" width="60%%">
                                                                        <tr>
                                                                            <td style="font-size:1px;line-height:1px;border-top:1px solid #5A6BA8;"><span>&#8202;</span></td>
                                                                        </tr>
                                                                    </table>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table width="100%%" border="0" cellpadding="10" cellspacing="0">
                                                        <tr>
                                                            <td>
                                                                <div align="center">
                                                                    <table width="156px" border="0" cellpadding="0" cellspacing="0" style="display:inline-block;">
                                                                        <tr>
                                                                            <td style="padding:0 10px;"><a href="https://www.facebook.com" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-outline-circle-white/facebook@2x.png" width="32" alt="Facebook" style="display:block; height:auto; border:0;"></a></td>
                                                                            <td style="padding:0 10px;"><a href="https://www.instagram.com" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-outline-circle-white/instagram@2x.png" width="32" alt="Instagram" style="display:block; height:auto; border:0;"></a></td>
                                                                            <td style="padding:0 10px;"><a href="https://www.twitter.com" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-outline-circle-white/twitter@2x.png" width="32" alt="Twitter" style="display:block; height:auto; border:0;"></a></td>
                                                                        </tr>
                                                                    </table>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table width="100%%" border="0" cellpadding="15" cellspacing="0">
                                                        <tr>
                                                            <td>
                                                                <div style="color:#4a60bb;font-family:'Varela Round', 'Trebuchet MS', Helvetica, sans-serif;font-size:12px;line-height:1.2;text-align:center;">
                                                                    <p style="margin:0;">Copyright © 2025 Your Brand, All rights reserved.<br><br>Where to find us: 2047 Roosevelt Road</p>
                                                                    <p style="margin:0;"><br>Changed your mind? You can <a href="http://www.example.com" target="_blank" title="unsubscribe" style="text-decoration:underline; color:#7f96ef;" rel="noopener">unsubscribe</a> at any time.</p>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table width="100%%" border="0" cellpadding="0" cellspacing="0">
                                                        <tr>
                                                            <td>
                                                                <div style="font-family:'Varela Round', 'Trebuchet MS', Helvetica, sans-serif;text-align:center;" align="center"><div style="height-top:20px;">&nbsp;</div></div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <!-- End Footer -->
                    <table align="center" width="100%%" border="0" cellpadding="0" cellspacing="0" style="background-color:#ffffff;">
                        <tbody>
                            <tr>
                                <td>
                                    <table align="center" border="0" cellpadding="0" cellspacing="0" style="width:600px; margin:0 auto; background-color:#ffffff; color:#000000;">
                                        <tbody>
                                            <tr>
                                                <td width="100%%" style="font-weight:400; text-align:left; padding-bottom:5px; padding-top:5px; vertical-align:top;">
                                                    <table width="100%%" border="0" cellpadding="0" cellspacing="0" style="text-align:center; line-height:0;">
                                                        <tr>
                                                            <td style="vertical-align:middle; color:#1e0e4b; font-family:'Inter', sans-serif; font-size:15px; padding-bottom:5px; padding-top:5px; text-align:center;">
                                                                <table style="display:inline-block; padding-left:0px; padding-right:0px;" cellpadding="0" cellspacing="0">
                                                                    <tr>
                                                                        <td style="vertical-align:middle; text-align:center; padding-top:5px; padding-bottom:5px; padding-left:5px; padding-right:6px;">
                                                                            <a href="http://designedwithbeefree.com/" target="_blank" style="text-decoration:none;">
                                                                                <img alt="Beefree Logo" src="https://d1oco4z2z1fhwp.cloudfront.net/assets/Beefree-logo.png" width="34" style="display:block; height:auto; margin:0 auto; border:0;">
                                                                            </a>
                                                                        </td>
                                                                        <td style="font-family:'Inter', sans-serif; font-size:15px; color:#1e0e4b; vertical-align:middle; text-align:center;">
                                                                            <a href="http://designedwithbeefree.com/" target="_blank" style="color:#1e0e4b; text-decoration:none;">Designed with Beefree</a>
                                                                        </td>
                                                                    </tr>
                                                                </table>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</body>
</html>
""".formatted(otpCode);
        try {
            SendMail.sendEmail(email, subject, body);
            JOptionPane.showMessageDialog(this, "Đã gửi lại mã xác thực về email!\nVui lòng kiểm tra hộp thư.");
            this.otpCode = newOtp; // Cập nhật mã OTP mới nhất
            this.otpCreatedTime = System.currentTimeMillis();
            startCountdown();
            disableResendOtp();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gửi email thất bại: " + ex.getMessage());
        }
    }//GEN-LAST:event_lblGuiLaiOTPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new OTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnContinue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblGuiLaiOTP;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtOTP;
    // End of variables declaration//GEN-END:variables
}
